version: '3.7'

services:
  main:
    container_name: waivio-objects-bot
    build: .
    command: npm run start
    restart: always
    network_mode: host
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    env_file:
      - .env
